export const FieldPerOptions = [
  { label: '신축허가', value: 2 },
  // { label: '증축허가', value: 2 },
  // { label: '개축허가', value: 3 },
  // { label: '재축허가', value: 4 },
  // { label: '대수선허가', value: 5 },
  // { label: '용도변경허가', value: 6 },
  // { label: '이전허가', value: 7 },
  // { label: '공용건축물', value: 8 },
  // { label: '협의건축물', value: 9 },
  // { label: '가설건축물허가', value: 10 },
  // { label: '재개발건축허가', value: 11 },
  // { label: '재건축허가', value: 12 },
  // { label: '주거환경협의허가', value: 13 },
  // { label: '주거환경지구허가', value: 14 },
  // { label: '개발제한건축허가', value: 15 },
  // { label: '개발제한가설허가', value: 16 },
  // { label: '행위허가신축', value: 17 },
  // { label: '행위허가증설', value: 18 },
  // { label: '행위허가개축', value: 19 },
  // { label: '행위허가 재축', value: 20 },
  // { label: '행위허가용도변경', value: 22 },
  // { label: '행위허가리모델링', value: 23 },
  // { label: '특정건축물신축', value: 24 },
  // { label: '특정건축물증축', value: 25 },
  // { label: '도시환경협의허가', value: 26 },
  // { label: '비연서신축허가', value: 27 },
  // { label: '연서신축허가', value: 28 },
];

export const FieldReportOptions = [
  { label: '신축신고', value: 1 },
  { label: '증축신고', value: 2 },
  { label: '개축신고', value: 3 },
  { label: '재축신고', value: 4 },
  { label: '대수선신고', value: 5 },
  { label: '용도변경신고', value: 6 },
  { label: '주거환경지구신고', value: 7 },
  { label: '개발제한구역신고', value: 8 },
  { label: '이전신고', value: 9 },
  { label: '가설건축물신고', value: 10 },
  { label: '행위신고용도변경', value: 11 },
  { label: '개발제한가설신고', value: 12 },
  { label: '발코니변경신고', value: 13 },
  { label: '행위신고증축', value: 14 },
  { label: '행위신고신축', value: 15 },
  { label: '행위신고철거', value: 16 },
];
